ibm-apic-gtw-instance:
  ibmapicgtwinstance:
    name: gateway
    spec:
      profile: n1xc1.m8
      apicGatewayServiceV5CompatibilityMode: true
      gatewayEndpoint:
        annotations:
          certmanager.k8s.io/issuer: ingress-issuer
        hosts:
          - name: gw-v5c.apps.philc-sandbox.cp.fyre.ibm.com
            secretName: gateway-endpoint-secret
      gatewayManagerEndpoint:
        annotations:
          certmanager.k8s.io/issuer: ingress-issuer
        hosts:
          - name: gwmanager-v5c.apps.philc-sandbox.cp.fyre.ibm.com
            secretName: gateway-manager-endpoint-secret
      apicGatewayServiceTLS:
        secretName: gateway-service-v5c
      apicGatewayPeeringTLS:
        secretName: gateway-peering-v5c
      datapowerLogLevel: 3
      license:
        accept: true
        license: L-GVEN-GFUPVE
        use: nonproduction
      tokenManagementService:
        enabled: true
        storage:
          storageClassName: rook-ceph-block
          volumeSize: 30Gi
      adminUser:
        secretName: admin-secret
      microServiceSecurity: certManager
      syslogConfig:
        enabled: false
        remoteHost: gateway.example.com
        remotePort: 200
        secretName: mySecretName
      # podAutoScaling:
      #   hpa:
      #     maxReplicas: 5
      #     minReplicas: 3
      #     targetCPUUtilizationPercentage: 80
      #     targetMemoryUtilizationPercentage: 80
      #   method: HPA
